# Generated by Django 5.1 on 2024-09-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_book_user_alter_book_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
